debug: False
fps: 10
max_frames: 600
save_every_n_frames: 10
host: localhost
port: 2000
tm_port: 8000
seed: 10
n_cpu: 20
bb_img: True      # save images with bounding boxes
panoptic: True    # save panoptic segmentation images

map: Town03
weather_presets_carla: ClearNoon
carla_presets: False
weather: clear    # possible presets: clear, rain, fog, night

#route_file: routes/town03.yaml

vehicles:
  num: 75
  excluded:
    - microlino
    - carlacola
    - cybertruck
    #- t2
    #- sprinter
    - firetruck
    - ambulance
    - isetta
    - police
    # -------- bicycles --------
    # - omafiets
    # - century
    # - crossbike
    # -------- motorcycles -----
    # - yzf
    # - low_rider
    # - ninja
  min_speed_difference: -20.0
  max_speed_difference: 30.0

pedestrians:
  num: 125
  cross_factor: 0.05

ego_vehicle:
  blueprint: vehicle.audi.tt

sensors:
  rgb:
    blueprint: sensor.camera.rgb
    attributes:
      image_size_x: 1920
      image_size_y: 1080
      motion_blur_intensity: 0.0
    location:
      x: 1.6
      z: 1.7
  depth:
    blueprint: sensor.camera.depth
    attributes:
      image_size_x: 1920
      image_size_y: 1080
    location:
      x: 1.6
      z: 1.7
  semantic:
    blueprint: sensor.camera.semantic_segmentation
    attributes:
      image_size_x: 1920
      image_size_y: 1080
    location:
      x: 1.6
      z: 1.7
  instance:
    blueprint: sensor.camera.instance_segmentation
    attributes:
      image_size_x: 1920
      image_size_y: 1080
    location:
      x: 1.6
      z: 1.7